-- Cargado si...
-- spring.r2dbc.initialization-mode=always
-- Pensado para cargar las tablas de h2 para test local

CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."SYSTEM_SEQUENCE_FC767D2B_DEEF_4EAC_852F_98F0952D0C8E" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE IF NOT EXISTS  "PUBLIC"."SYSTEM_SEQUENCE_099EEBE3_1B61_4DC0_826D_222EC07DFBE7" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE IF NOT EXISTS  "PUBLIC"."SYSTEM_SEQUENCE_2FC045AD_1BBA_40DA_8665_9AF0B9AE1969" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE IF NOT EXISTS  "PUBLIC"."SYSTEM_SEQUENCE_92A4AD1B_F769_419C_8BE5_4AAC6746CBBC" START WITH 1 BELONGS_TO_TABLE;


CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."LEARNING_PATH"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_92A4AD1B_F769_419C_8BE5_4AAC6746CBBC" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_92A4AD1B_F769_419C_8BE5_4AAC6746CBBC",
    "NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" CLOB,
    "ENABLED" BOOLEAN,
    "LEVEL" INT
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."COURSE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_2FC045AD_1BBA_40DA_8665_9AF0B9AE1969" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2FC045AD_1BBA_40DA_8665_9AF0B9AE1969",
    "UDEMY_ID" BIGINT,
    "TITLE" VARCHAR(255),
    "DESCRIPTION" CLOB,
    "ESTIMATED_CONTENT_LENGTH" INT,
    "NUM_LECTURES" INT,
    "NUM_QUIZZES" INT,
    "NUM_PRACTICE_TESTS" INT,
    "EXPECTED_SCORE" INT
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."COURSE_LEARNING_PATH"(
    "LEARNING_PATH_ID" BIGINT NOT NULL,
    "COURSE_ID" BIGINT NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_099EEBE3_1B61_4DC0_826D_222EC07DFBE7" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_099EEBE3_1B61_4DC0_826D_222EC07DFBE7",
    "NAME" VARCHAR(255)
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."USER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_FC767D2B_DEEF_4EAC_852F_98F0952D0C8E" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_FC767D2B_DEEF_4EAC_852F_98F0952D0C8E",
    "LOGIN" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "LOGIN_ENABLED" BOOLEAN DEFAULT FALSE,
    "LEVEL" INT,
    "PEOPLE_LEAD" VARCHAR(255),
    "RESET_PASSWORD" VARCHAR(255)
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."ROLE_USER"(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."COURSE_USER_SNAPSHOT"(
    "USER_ID" BIGINT NOT NULL,
    "COURSE_ID" BIGINT NOT NULL,
    "SNAP_DATE" TIMESTAMP NOT NULL,
    "COMPLETION_RATIO" DOUBLE,
    "NUM_VIDEO_CONSUMED_MINUTES" INT,
    "COURSE_ENROLL_DATE" TIMESTAMP,
    "COURSE_START_DATE" TIMESTAMP,
    "COURSE_COMPLETION_DATE" TIMESTAMP,
    "COURSE_FIRST_COMPLETION_DATE" TIMESTAMP
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."LEARNING_PATH_USER"(
    "USER_ID" BIGINT NOT NULL,
    "LEARNING_PATH_ID" BIGINT NOT NULL
);