-- Cargado si...
-- spring.r2dbc.initialization-mode=always
-- Pensado para cargar las tablas de h2 para test local

CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."SYSTEM_SEQUENCE_784E57F6_2DE3_4521_A024_B835FA35D4E1" START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."COURSE"(
    "ID" BIGINT NOT NULL,
    "TITLE" VARCHAR(255),
    "DESCRIPTION" CLOB,
    "ESTIMATED_CONTENT_LENGTH" INT,
    "NUM_LECTURES" INT,
    "NUM_QUIZZES" INT,
    "NUM_PRACTICE_TESTS" INT,
    "EXPECTED_SCORE" INT
);

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."LEARNING_PATH"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_784E57F6_2DE3_4521_A024_B835FA35D4E1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_784E57F6_2DE3_4521_A024_B835FA35D4E1",
    "NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" CLOB,
    "ENABLED" BOOLEAN,
    "LEVEL" INT
);

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."COURSE_LEARNING_PATH"(
    "LEARNING_PATH_ID" BIGINT NOT NULL,
    "COURSE_ID" BIGINT NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."ROLE"(
    "NAME" VARCHAR(255) NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."USER"(
    "LOGIN" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255),
    "LOGIN_ENABLED" BOOLEAN DEFAULT FALSE,
    "LEVEL" INT,
    "PEOPLE_LEAD" VARCHAR(255),
    "RESET_PASSWORD" VARCHAR(255)
);

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."ROLE_USER"(
    "USER_LOGIN" VARCHAR(255) NOT NULL,
    "ROLE_NAME" VARCHAR(255) NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."COURSE_USER_SNAPSHOT"(
    "USER_LOGIN" VARCHAR(255) NOT NULL,
    "COURSE_ID" BIGINT NOT NULL,
    "SNAP_DATE" TIMESTAMP NOT NULL,
    "COMPLETION_RATIO" DOUBLE,
    "NUM_VIDEO_CONSUMED_MINUTES" INT,
    "COURSE_ENROLL_DATE" TIMESTAMP,
    "COURSE_START_DATE" TIMESTAMP,
    "COURSE_COMPLETION_DATE" TIMESTAMP,
    "COURSE_FIRST_COMPLETION_DATE" TIMESTAMP
);

CREATE CACHED TABLE IF NOT EXISTS "PUBLIC"."LEARNING_PATH_USER"(
    "USER_LOGIN" VARCHAR(255) NOT NULL,
    "LEARNING_PATH_ID" BIGINT NOT NULL
);


