-- Cargado si...
-- spring.r2dbc.initialization-mode=always
-- Pensado para cargar las tablas de h2 para test local

CREATE SEQUENCE IF NOT EXISTS "PUBLIC"."SYSTEM_SEQUENCE_MASTER_SEQUENCE" START WITH 1 BELONGS_TO_TABLE;

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."ACCOUNT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_MASTER_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_MASTER_SEQUENCE",
    "ENTERPRISE_ID" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255),
    "PEOPLE_LEAD_EID" VARCHAR(255),
    "PEOPLE_LEAD_EMAIL" VARCHAR(255),
    "LEVEL" INT
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."LEARNING_PATH"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_MASTER_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_MASTER_SEQUENCE",
    "NAME" VARCHAR(255) NOT NULL,
    "DESCRIPTION" CLOB,
    "LEVEL" INT
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."COURSE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_MASTER_SEQUENCE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_MASTER_SEQUENCE",
    "UDEMY_ID" BIGINT NOT NULL,
    "TITLE" VARCHAR(255),
    "DESCRIPTION" CLOB,
    "ESTIMATED_CONTENT_LENGTH" INT,
    "NUM_LECTURES" INT,
    "NUM_QUIZZES" INT,
    "NUM_PRACTICE_TESTS" INT,
    "EXPECTED_SCORE" INT
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."COURSE_LEARNING_PATH"(
    "LEARNING_PATH_ID" BIGINT NOT NULL,
    "COURSE_ID" BIGINT NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS  "PUBLIC"."ACCOUNT_LEARNING_PATH"(
    "ACCOUNT_ID" BIGINT NOT NULL,
    "LEARNING_PATH_ID" BIGINT NOT NULL
);
